require('dotenv').config();
const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const cors = require('cors');
const path = require('path');
const https = require('https');
const crypto = require('crypto');
const fs = require('fs');
const { execFile, exec: execShell } = require('child_process');
const { PORT } = require('./src/config');

const app = express();
const server = http.createServer(app);
const io = new Server(server, {
    cors: { origin: "*" }
});

app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

app.use((req, res, next) => {
    req.io = io;
    next();
});

// --- API ROUTES ---
const healthRoutes = require('./src/routes/health');
const questRoutes = require('./src/routes/quests');
const financeRoutes = require('./src/routes/finance');
const habitRoutes = require('./src/routes/habits');
const focusRoutes = require('./src/routes/focus');
const taskRoutes = require('./src/routes/tasks');
const bloodPressureRoutes = require('./src/routes/bloodPressure');
const explorerRoutes = require('./src/routes/explorer');
const insightRoutes = require('./src/routes/insights');
const blueprintRoutes = require('./src/routes/blueprint');
const beliefRoutes = require('./src/routes/beliefs');
const protocolRoutes = require('./src/routes/protocols');
const savoringRoutes = require('./src/routes/savoring');

app.use('/api', healthRoutes);
app.use('/api', questRoutes);
app.use('/api', financeRoutes);
app.use('/api', habitRoutes);
app.use('/api', focusRoutes);
app.use('/api', taskRoutes);
app.use('/api', bloodPressureRoutes);
app.use('/api/explorer', explorerRoutes);
app.use('/api/insights', insightRoutes);
app.use('/api/blueprint', blueprintRoutes);
app.use('/api', beliefRoutes);
app.use('/api', protocolRoutes);
app.use('/api', savoringRoutes);

// --- STATIC FILES ---
app.use(express.static(path.join(__dirname, 'client/dist')));

// Serve OpenClaw TTS files (Temporary location)
// This allows the dashboard to play audio files generated by OpenClaw
app.use('/audio/tts', express.static('/tmp/openclaw'));

// --- AUTOMATIC TTS WATCHER ---
// Scans /tmp/openclaw for new .mp3 files and broadcasts them automatically.
// This allows the dashboard to "pull" new voice responses without explicit API calls.
let lastPlayedFile = null;
let lastPlayedTime = Date.now();
let lastAgentMessageTime = 0; // Tracks when a chat message was sent to OpenClaw
let pendingFiles = {}; // Track files being written: { path: { size, mtimeMs } }

function scanForNewAudio() {
    const ttsDir = '/tmp/openclaw';
    if (!fs.existsSync(ttsDir)) return;

    // If an agent message was just sent, skip the watcher for a few seconds 
    // to give the dashboard's immediate stream priority.
    // Increased to 60s to account for slow ElevenLabs generations.
    if (Date.now() - lastAgentMessageTime < 60000) {
        return;
    }

    try {
        const subdirs = fs.readdirSync(ttsDir).filter(d => d.startsWith('tts-') && d !== 'tts-dashboard' && d !== 'tts-cache');
        let currentFiles = {};

        for (const subdir of subdirs) {
            const fullSubdir = path.join(ttsDir, subdir);
            const files = fs.readdirSync(fullSubdir).filter(f => f.endsWith('.mp3'));
            
            for (const file of files) {
                const filePath = path.join(fullSubdir, file);
                const stats = fs.statSync(filePath);
                const relPath = `${subdir}/${file}`;
                
                // Only consider files newer than the last played time
                if (stats.mtimeMs > lastPlayedTime && relPath !== lastPlayedFile) {
                    currentFiles[relPath] = {
                        size: stats.size,
                        mtimeMs: stats.mtimeMs
                    };
                }
            }
        }

        // Check pending files to see if their size has stabilized
        for (const [relPath, data] of Object.entries(currentFiles)) {
            if (pendingFiles[relPath]) {
                // If size hasn't changed since last tick, increment stable ticks
                if (pendingFiles[relPath].size === data.size && data.size > 0) {
                    const ticks = (pendingFiles[relPath].stableTicks || 0) + 1;
                    
                    // Require size to be stable for at least 4 ticks (4 seconds)
                    if (ticks >= 4) {
                        console.log(`[TTS Watcher] Audio fully written after ${ticks}s, broadcasting: ${relPath}`);
                        lastPlayedFile = relPath;
                        lastPlayedTime = data.mtimeMs;
                        
                        io.emit('ttsPlay', { 
                            // Add cache buster to prevent browser from caching a potentially incomplete file
                            url: `/audio/tts/${relPath}?t=${Date.now()}`,
                            text: 'Auto-detected new voice file'
                        });
                        
                        // Clear pending after playing to avoid re-triggering
                        delete pendingFiles[relPath];
                        break; // Only play one new file per tick to avoid overlap
                    } else {
                        pendingFiles[relPath].stableTicks = ticks;
                    }
                } else {
                    // Size changed, reset stable ticks and update size
                    pendingFiles[relPath] = { ...data, stableTicks: 0 };
                }
            } else {
                // New file detected, add to pending list
                pendingFiles[relPath] = { ...data, stableTicks: 0 };
            }
        }
        
        // Cleanup old pending files that are no longer in currentFiles
        for (const relPath in pendingFiles) {
            if (!currentFiles[relPath]) {
                delete pendingFiles[relPath];
            }
        }
    } catch (err) {
        // Silent fail for directory read errors
    }
}

// Scan frequently to quickly catch when size stabilizes
setInterval(scanForNewAudio, 1000);

// --- TTS BROADCAST ENDPOINT ---
// Allows OpenClaw or other scripts to trigger audio playback on all connected dashboards
app.post('/api/tts/broadcast', (req, res) => {
    const { filename, text } = req.body;
    console.log(`[TTS Broadcast] Received: filename="${filename}", text="${text}"`);
    
    if (!filename) {
        return res.status(400).json({ error: 'Filename is required' });
    }
    
    // If an agent message was recently sent and this broadcast has no text,
    // it's likely a redundant duplicate from the agent CLI. Skip it.
    // Increased to 60s to match watcher.
    if (Date.now() - lastAgentMessageTime < 60000 && !text) {
        console.log(`[TTS Broadcast] Ignoring text-less broadcast during active agent session to prevent stutter.`);
        return res.json({ success: true, message: 'Broadcast ignored (redundant during active chat)' });
    }

    // Broadcast the event to all connected Socket.io clients
    req.io.emit('ttsPlay', { 
        url: filename.startsWith('http') ? filename : `/audio/tts/${filename}`,
        text: text || ''
    });

    // Update the watcher state to prevent re-playing the same file if it's in /tmp/openclaw
    lastPlayedFile = filename;
    lastPlayedTime = Date.now();
    
    res.json({ success: true, message: 'TTS playback broadcasted' });
});

// --- OPENCLAW CHAT ENDPOINT ---
// Allows the dashboard to send a text message directly to the local OpenClaw session

// --- TTS ENGINES ---

async function generateOpenAITTS(text, filePath) {
    const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
    const VOICE = "marin"; // User requested Marin voice (2026 model)

    return new Promise((resolve) => {
        if (!OPENAI_API_KEY) {
            console.warn(`[TTS] No OPENAI_API_KEY found in .env. Skipping OpenAI...`);
            return resolve(false);
        }

        console.log(`[TTS] Attempting OpenAI generation (Voice: ${VOICE})...`);

        const postData = JSON.stringify({
            model: "gpt-4o-mini-tts", // gpt-4o-mini-tts supports marin on v1/audio/speech
            voice: VOICE,
            input: text
        });

        const options = {
            hostname: 'api.openai.com',
            path: '/v1/audio/speech',
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${OPENAI_API_KEY}`,
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(postData)
            }
        };

        const req = https.request(options, (res) => {
            if (res.statusCode === 200) {
                const fileStream = fs.createWriteStream(filePath);
                res.pipe(fileStream);
                fileStream.on('finish', () => {
                    console.log(`[TTS] OpenAI success: ${filePath}`);
                    resolve(true);
                });
            } else {
                let errorBody = '';
                res.on('data', (chunk) => { errorBody += chunk; });
                res.on('end', () => {
                    console.error(`[TTS] OpenAI failed (Status: ${res.statusCode}). Body: ${errorBody}.`);
                    resolve(false);
                });
            }
        });

        req.on('error', (e) => {
            console.error(`[TTS] OpenAI request error: ${e.message}.`);
            resolve(false);
        });

        req.write(postData);
        req.end();
    });
}

async function generateElevenLabsTTS(text, filePath, voiceId) {
    const ELEVEN_LABS_API_KEY = process.env.ELEVEN_LABS_API_KEY;
    const ELEVEN_LABS_VOICE_ID = voiceId || process.env.ELEVEN_LABS_VOICE_ID || "MClEFoImJXBTgLwdLI5n";

    return new Promise((resolve) => {
        if (!ELEVEN_LABS_API_KEY) {
            console.warn(`[TTS] No ELEVEN_LABS_API_KEY found. Skipping ElevenLabs...`);
            return resolve(false);
        }

        console.log(`[TTS] Attempting ElevenLabs generation...`);

        const postData = JSON.stringify({
            text: text,
            model_id: "eleven_v3",
            voice_settings: {
                stability: 0.5,
                similarity_boost: 0.75
            }
        });

        const options = {
            hostname: 'api.elevenlabs.io',
            path: `/v1/text-to-speech/${ELEVEN_LABS_VOICE_ID}`,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'xi-api-key': ELEVEN_LABS_API_KEY,
                'Content-Length': Buffer.byteLength(postData)
            }
        };

        const req = https.request(options, (res) => {
            if (res.statusCode === 200) {
                const fileStream = fs.createWriteStream(filePath);
                res.pipe(fileStream);
                fileStream.on('finish', () => {
                    console.log(`[TTS] ElevenLabs success: ${filePath}`);
                    resolve(true);
                });
            } else {
                let errorBody = '';
                res.on('data', (chunk) => { errorBody += chunk; });
                res.on('end', () => {
                    console.error(`[TTS] ElevenLabs failed (Status: ${res.statusCode}). Body: ${errorBody}.`);
                    resolve(false);
                });
            }
        });

        req.on('error', (e) => {
            console.error(`[TTS] ElevenLabs request error: ${e.message}.`);
            resolve(false);
        });

        req.write(postData);
        req.end();
    });
}

async function generateEdgeTTS(text, filePath) {
    console.log(`[TTS] Using Microsoft Edge...`);
    const ttsCmd = `/home/maranta/.npm-global/lib/node_modules/openclaw/node_modules/.bin/node-edge-tts --voice "en-AU-NatashaNeural" --rate "+20%" --text ${JSON.stringify(text)} --filepath "${filePath}"`;
    return new Promise((resolve) => {
        execShell(ttsCmd, (ttsErr) => {
            if (ttsErr) {
                console.error(`[TTS] Edge failed: ${ttsErr.message}`);
                resolve(false);
            } else {
                console.log(`[TTS] Edge success: ${filePath}`);
                resolve(true);
            }
        });
    });
}

// Helper to generate TTS with fallback
async function generateTTSWithFallback(text, filePath, preferredEngine = 'openai', voiceId = null) {
    let success = false;

    if (preferredEngine === 'openai') {
        success = await generateOpenAITTS(text, filePath);
    } else if (preferredEngine === 'elevenlabs') {
        success = await generateElevenLabsTTS(text, filePath, voiceId);
    } else if (preferredEngine === 'edge') {
        success = await generateEdgeTTS(text, filePath);
    }

    // Fallback if preferred failed or wasn't specified
    if (!success && preferredEngine !== 'openai') {
        success = await generateOpenAITTS(text, filePath);
    }
    
    if (!success && preferredEngine !== 'elevenlabs') {
        // Only try ElevenLabs as fallback if we have a key
        if (process.env.ELEVEN_LABS_API_KEY) {
            success = await generateElevenLabsTTS(text, filePath, voiceId);
        }
    }

    if (!success) {
        success = await generateEdgeTTS(text, filePath);
    }

    return success;
}

// --- STREAMING TTS ENDPOINT ---
app.get('/api/tts/stream', async (req, res) => {
    const { text, engine = 'openai', voiceId } = req.query;
    if (!text) return res.status(400).send('Text is required');

    const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
    const ELEVEN_LABS_API_KEY = process.env.ELEVEN_LABS_API_KEY;
    const DEFAULT_ELEVEN_LABS_VOICE_ID = process.env.ELEVEN_LABS_VOICE_ID || "MClEFoImJXBTgLwdLI5n";
    const selectedVoiceId = (engine === 'elevenlabs' && voiceId) ? voiceId : DEFAULT_ELEVEN_LABS_VOICE_ID;

    // Cache logic to prevent duplicate API calls for the exact same message
    const cacheKey = crypto.createHash('md5').update(`${text}_${engine}_${selectedVoiceId}`).digest('hex');
    const cacheDir = '/tmp/openclaw/tts-cache';
    const cacheFile = path.join(cacheDir, `${cacheKey}.mp3`);

    if (!fs.existsSync(cacheDir)) {
        fs.mkdirSync(cacheDir, { recursive: true });
    }

    if (fs.existsSync(cacheFile)) {
        console.log(`[TTS Stream] Serving cached audio for replay: ${cacheKey}`);
        res.setHeader('Content-Type', 'audio/mpeg');
        return fs.createReadStream(cacheFile).pipe(res);
    }

    if (engine === 'openai' && OPENAI_API_KEY) {
        console.log(`[TTS Stream] Streaming from OpenAI (Marin)...`);
        const postData = JSON.stringify({
            model: "gpt-4o-mini-tts",
            voice: "marin",
            input: text
        });

        const options = {
            hostname: 'api.openai.com',
            path: '/v1/audio/speech',
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${OPENAI_API_KEY}`,
                'Content-Type': 'application/json'
            }
        };

        const aiReq = https.request(options, (aiRes) => {
            res.setHeader('Content-Type', 'audio/mpeg');
            // Save to cache while streaming to client
            const fileStream = fs.createWriteStream(cacheFile);
            aiRes.pipe(fileStream);
            aiRes.pipe(res);
        });

        aiReq.on('error', (e) => {
            console.error(`[TTS Stream] OpenAI error: ${e.message}`);
            res.status(500).send('Streaming failed');
        });

        aiReq.write(postData);
        aiReq.end();
    } else if (engine === 'elevenlabs' && ELEVEN_LABS_API_KEY) {
        console.log(`[TTS Stream] Streaming from ElevenLabs (${selectedVoiceId})...`);
        const postData = JSON.stringify({
            text: text,
            model_id: "eleven_v3",
            voice_settings: {
                stability: 0.5,
                similarity_boost: 0.75
            }
        });

        const options = {
            hostname: 'api.elevenlabs.io',
            path: `/v1/text-to-speech/${selectedVoiceId}/stream`,
            method: 'POST',
            headers: {
                'xi-api-key': ELEVEN_LABS_API_KEY,
                'Content-Type': 'application/json'
            }
        };

        const aiReq = https.request(options, (aiRes) => {
            if (aiRes.statusCode !== 200) {
                console.error(`[TTS Stream] ElevenLabs error status: ${aiRes.statusCode}`);
                let errorData = '';
                aiRes.on('data', d => errorData += d);
                aiRes.on('end', () => console.error(`[TTS Stream] ElevenLabs error body: ${errorData}`));
                return res.status(aiRes.statusCode).send('ElevenLabs streaming failed');
            }
            res.setHeader('Content-Type', 'audio/mpeg');
            // Save to cache while streaming to client
            const fileStream = fs.createWriteStream(cacheFile);
            aiRes.pipe(fileStream);
            aiRes.pipe(res);
        });

        aiReq.on('error', (e) => {
            console.error(`[TTS Stream] ElevenLabs request error: ${e.message}`);
            res.status(500).send('Streaming failed');
        });

        aiReq.write(postData);
        aiReq.end();
    } else {
        // Fallback to pre-generated or edge? For now, we focus on OpenAI streaming
        res.status(400).send('Streaming only supported for OpenAI currently');
    }
});

app.post('/api/openclaw/message', (req, res) => {
    const { message, ttsEngine = 'openai', voiceId } = req.body;
    
    // Mute the watcher briefly while we process this chat message
    lastAgentMessageTime = Date.now();

    if (!message || typeof message !== 'string') {
        return res.status(400).json({ error: 'Message text is required' });
    }

    console.log(`[OpenClaw] Sending message: "${message}" (TTS Engine: ${ttsEngine}, Voice: ${voiceId || 'default'})`);
    
    // Use execFile instead of exec to avoid shell injection and quoting issues
    const args = ['agent', '--session-id', 'personal', '--message', message, '--json'];
    
    execFile('/home/maranta/.npm-global/bin/openclaw', args, (error, stdout, stderr) => {
        if (error) {
            console.error(`[OpenClaw] Error executing command: ${error.message}`);
            return res.status(500).json({ error: 'Failed to communicate with OpenClaw' });
        }
        
        try {
            // Try to parse the JSON response from OpenClaw
            // Extract the largest possible JSON block (from first { to last })
            const firstBrace = stdout.indexOf('{');
            const lastBrace = stdout.lastIndexOf('}');
            
            let responseData = null;
            if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
                const jsonStr = stdout.substring(firstBrace, lastBrace + 1);
                try {
                    responseData = JSON.parse(jsonStr);
                    console.log(`[OpenClaw] Successfully parsed JSON response (${jsonStr.length} chars)`);
                } catch (parseErr) {
                    console.error(`[OpenClaw] JSON Parse error: ${parseErr.message}`);
                    // If full block fails, try matching smaller blocks as a fallback
                    const jsonMatches = stdout.match(/\{[\s\S]*?\}/g) || [];
                    for (const match of jsonMatches) {
                        try {
                            const parsed = JSON.parse(match);
                            if (parsed.result || parsed.payloads || parsed.text) {
                                responseData = parsed;
                                break;
                            }
                        } catch (e) {}
                    }
                }
            }
            
            if (!responseData) {
                responseData = { text: stdout.trim() || stderr.trim() || "Ruby processed the message but returned no output." };
            }
            
            let agentText = null;
            
            // Extract and concatenate all text payloads returned by the agent
            if (responseData.result && responseData.result.payloads) {
                const textParts = responseData.result.payloads
                    .filter(p => p.text)
                    .map(p => p.text);
                
                if (textParts.length > 0) {
                    agentText = textParts.join('\n\n');
                    console.log(`[OpenClaw] Agent replied with ${textParts.length} text parts.`);
                }
            } else if (responseData.payloads) {
                // Handle direct payloads (non-result wrapped)
                const textParts = responseData.payloads
                    .filter(p => p.text)
                    .map(p => p.text);
                
                if (textParts.length > 0) {
                    agentText = textParts.join('\n\n');
                }
            } else if (responseData.text) {
                agentText = responseData.text; 
            } else if (typeof responseData === 'string') {
                agentText = responseData;
            }

            if (!agentText) {
                console.log(`[OpenClaw] Agent replied with empty/unrecognized format. Raw stdout: ${stdout.substring(0, 200)}...`);
                agentText = "Ruby processed your request but the response format was unrecognized.";
            }
            
            // --- STREAMING TRIGER ---
            // If the agent replied with text, tell the client to stream the audio IMMEDIATELY
            if (agentText && agentText !== "Ruby processed your request but the response format was unrecognized.") {
                // Aggressively clean the text for natural speech synthesis
                let cleanText = agentText
                    .replace(/\*\*/g, '')          
                    .replace(/\*/g, '')            
                    .replace(/__/g, '')            
                    .replace(/_/g, '')             
                    .replace(/`/g, '')             
                    .replace(/^-\s/gm, '')         
                    .replace(/#/g, '')             
                    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') 
                    .replace(/\n/g, '. ')          
                    .replace(/\s+/g, ' ')          
                    .trim();

                // If NOT using ElevenLabs, strip the [tag] speech markers so they aren't spoken literally
                if (ttsEngine !== 'elevenlabs') {
                    cleanText = cleanText.replace(/\[[a-zA-Z\s]+\]/g, '');
                }

                console.log(`[OpenClaw] Triggering immediate TTS stream for response...`);
                io.emit('ttsPlay', { 
                    url: `/api/tts/stream?text=${encodeURIComponent(cleanText)}&engine=${ttsEngine}&voiceId=${voiceId || ''}&t=${Date.now()}`,
                    text: agentText // Send original text for UI display
                });

                // Update watcher state to prevent re-playing what we just streamed
                // The agent might have saved a file to /tmp/openclaw during its run
                lastPlayedTime = Date.now();
                lastPlayedFile = `stream-${Date.now()}`;

                // Background: Still save to file for history/archival if desired, but don't wait for it
                const ttsDir = '/tmp/openclaw/tts-dashboard';
                if (!fs.existsSync(ttsDir)) fs.mkdirSync(ttsDir, { recursive: true });
                const fileName = `voice-${Date.now()}.mp3`;
                const filePath = `${ttsDir}/${fileName}`;
                generateTTSWithFallback(cleanText, filePath, ttsEngine, voiceId);
            }
            
            res.json({ success: true, response: responseData, text: agentText });
        } catch (e) {
            console.error(`[OpenClaw] Error parsing response: ${e.message}`);
            res.json({ success: true, textResponse: stdout }); // Fallback
        }
    });
});

// --- SPA CATCH-ALL (Middleware style to avoid wildcard errors) ---
app.use((req, res) => {
    res.sendFile(path.join(__dirname, 'client/dist', 'index.html'));
});

// --- START SERVER ---
const focusService = require('./src/services/focusService');
focusService.initDb().then(() => {
    server.listen(PORT, () => {
        console.log(`Life RPG Dashboard running on http://localhost:${PORT}`);
    });
}).catch(err => {
    console.error("Failed to initialize DB and start server:", err);
    process.exit(1);
});

io.on('connection', (socket) => {
    console.log('Dashboard client connected');
    socket.on('disconnect', () => console.log('Dashboard client disconnected'));
});
